---
- name: Install dovecot packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-sieve

- name: Ensure mail group exists
  group:
    name: mail
    gid: 8
    state: present

- name: Ensure vmail user exists
  user:
    name: vmail
    shell: /bin/false
    home: /home/vmail
    uid: 5000
    group: mail
    state: present

- name: Ensure /etc/dovecot/sieve directory exists
  file:
    state: directory
    path: /etc/dovecot/sieve
    mode: 0755
    owner: dovecot
    group: root

- name: Configure dovecot
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: dovecot
    group: root
  with_items:
    - { src: "dovecot.conf.j2", dest: "/etc/dovecot/dovecot.conf" }
    - { src: "global.sieve.j2", dest: "/etc/dovecot/sieve/global.sieve" }

- name: Compile dovecot global.sieve
  shell: "/usr/bin/sievec {{ item }} 2>/dev/null"
  with_items:
    - /etc/dovecot/sieve/global.sieve

- name: Ensure dovecot.log exists and that mail (gid 8) has access
  file:
    path: /var/log/dovecot.log
    state: touch
    mode: 0664
    owner: dovecot
    group: mail

- name: Add logrotate job for dovecot.log
  template:
    src: logrotate_dovecot.j2
    dest: /etc/logrotate.d/dovecot
    mode: 0644

- name: Ensure dovecot ssl directory exists
  file:
    path: "{{ dovecot_ssl_dir }}"
    state: directory
    mode: 0755
    owner: dovecot
    group: root
  when: manage_mail_certs | bool == true

- name: Create SSL certificate files
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ dovecot_ssl_dir }}/{{ item.filename }}"
    mode: "{{ item.mode }}"
    owner: dovecot
    group: root
  with_items:
    - { filename: "ca.pem", mode: "0644" }
    - { filename: "cert.pem", mode: "0644" }
    - { filename: "key.pem", mode: "0400" }
  when: manage_mail_certs | bool == true

- name: Ensure dovecot is enabled and running
  service:
    name: dovecot
    state: restarted
    enabled: yes
