---
- name: Install nginx
  package:
    name: nginx-full
    state: latest

- name: Install haveged for entropy
  package:
    name: haveged
    state: latest

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Disable default vhost...
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure roundcube vhost
  template:
    src: roundcube.conf.j2
    dest: /etc/nginx/sites-available/roundcube.conf
    mode: 0644

- name: Enable roundcube vhost
  file:
    src: /etc/nginx/sites-available/roundcube.conf
    dest: /etc/nginx/sites-enabled/roundcube.conf
    state: link

- name: Ensure nginx-roundcube ssl directory exists
  file:
    path: "{{ nginx_roundcube_ssl_dir }}"
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Create SSL certificate files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: "cert.pem.j2", dest: "{{ nginx_roundcube_ssl_dir }}/cert.pem", mode: "0644" }
    - { src: "key.pem.j2", dest: "{{ nginx_roundcube_ssl_dir }}/key.pem", mode: "0600" }

- name: Generate dhparams.pem (one-time only, takes long time...)
  shell:
    cmd: /bin/openssl dhparam -out /etc/nginx/dhparam.pem 4096
    creates: /etc/nginx/dhparam.pem

- name: Ensure nginx service is enabled and running
  service:
    name: nginx
    enabled: yes
    state: restarted
