---
- name: Install rsyslog package
  apt:
    name: rsyslog
    state: latest

- name: Install python3-pip package
  apt:
    name: python3-pip
    state: latest

- name: Install python dependencies
  pip:
    name:
      - requests
      - setuptools
      - pip
      - ipaddr
    state: latest
    virtualenv: "{{ denyhosts_path }}/venv"

- name: Remove old denyhosts config
  file:
    name: /etc/denyhosts.conf
    state: absent
    
- name: "Install denyhosts from github.com/{{ denyhosts_orgname }}/{{ denyhosts_reponame }}.git@{{ denyhosts_branch }}"
  pip:
    name: "git+https://github.com/{{ denyhosts_orgname }}/{{ denyhosts_reponame }}.git@{{ denyhosts_branch }}#egg=DenyHosts"
    virtualenv: "{{ denyhosts_path }}/venv"

- name: Ensure /var/lib/denyhosts exists
  file:
    state: directory
    path: /var/lib/denyhosts
    mode: 0755

- name: Configure denyhosts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: "denyhosts.conf-{{ denyhosts_branch }}.j2", dest: "/etc/denyhosts.conf" }
    - { src: "allowed-hosts.j2", dest: "/var/lib/denyhosts/allowed-hosts" }
    - { src: "restricted-usernames.j2", dest: "/var/lib/denyhosts/restricted-usernames" }

- name: Add logrotate job for denyhosts.log
  template:
    src: logrotate_denyhosts.j2
    dest: /etc/logrotate.d/denyhosts
    mode: 0644

- name: Create denyhosts systemd service
  template:
    src: denyhosts.service.j2
    dest: /etc/systemd/system/denyhosts.service
    mode: 0644

- name: Issue systemctl daemon-reload in case unit file changed
  systemd:
    daemon_reload: yes

- name: Ensure rsyslog is enabled and running
  service:
    name: rsyslog
    enabled: yes
    state: restarted

- name: Ensure denyhosts is enabled and running
  service:
    name: denyhosts
    enabled: yes
    state: restarted

- name: Create iptables wrapper script (optional)
  template:
    src: iptables-wrapper.sh.j2
    dest: "{{ denyhosts_iptables_wrapper }}"
    mode: 0755
  when: denyhosts_iptables_wrapper is defined
