---
- hosts: all
  vars:
    php_service_name:
      stretch: "php7.0-fpm"
      buster: "php7.3-fpm"
  roles:
    - roundcube
  post_tasks:
    - name: Ensure php-fpm service is enabled and running
      service:
        name: "{{ php_service_name[ansible_distribution_release] }}"
        state: restarted
