---
roles:
  - name: docker
    version: 7.4.7
    src: https://github.com/geerlingguy/ansible-role-docker
  - name: node_exporter
    version: 2.1.2
    src: https://github.com/geerlingguy/ansible-role-node_exporter
