---
- name: Install php-fpm packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php_packages[ansible_distribution_release] }}"

- name: Configure php-fpm
  template:
    src: php.ini.j2
    dest: "{{ php_conf_dir[ansible_distribution_release] }}/php.ini"
    mode: 0644

- name: Ensure php-fpm service is enabled and running
  systemd:
    name: "{{ php_service_name[ansible_distribution_release] }}"
    enabled: yes
    state: restarted
