---
- name: Install postfix packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - postfix
    - postfix-pcre

- name: Configure postfix
  template:
    src: "{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
    mode: 0644
    owner: root
    group: postfix
  with_items:
    - main.cf
    - master.cf
    - blackwhite.map
    - valias.map
    - virtual.map
    - header_checks
    - body_checks

- name: Configure smtpd sasl
  template:
    src: smtpd.conf.j2
    dest: /etc/postfix/sasl/smtpd.conf
    mode: 0644
    owner: root
    group: postfix

- name: Compile postfix maps
  shell: "/usr/sbin/postmap {{ item }} 2>/dev/null"
  args:
    chdir: /etc/postfix
  with_items:
    - blackwhite.map
    - valias.map
    - virtual.map

- name: Generate custom DH parameters file
  shell: "openssl dhparam -out /etc/postfix/dh2048.pem 2048"
  args:
    creates: /etc/postfix/dh2048.pem

- name: Set DH parameters file permissions
  file:
    path: '/etc/postfix/dh2048.pem'
    owner: root
    group: postfix 
    mode: '0640'

- name: Run postfix set-permissions
  shell: "/sbin/postfix set-permissions"

- name: Ensure postfix is started and enabled
  service:
    name: postfix
    enabled: yes
    state: restarted
