---

fqdn_hostname: ""

mail_ssl_dir: /opt/certbot/haproxy_fullchains
mail_domain: pcdomain.com

postfix_ssl_ca_file: "{{ mail_ssl_dir }}/pcdomain.com.pem"
postfix_ssl_cert_file: "{{ mail_ssl_dir }}/pcdomain.com.pem"
postfix_ssl_key_file: "{{ mail_ssl_dir }}/pcdomain.com.pem"

nginx_roundcube_server_port: 443
roundcube_previous_version: "1.4.10"

dovecot_ssl_dir: "{{ mail_ssl_dir }}"
postfix_ssl_dir: "{{ mail_ssl_dir }}"
roundcube_ssl_dir: "{{ mail_ssl_dir }}"

dovecot_domain: "{{ mail_domain }}"
postfix_domain: "{{ mail_domain }}"
roundcube_domain: "{{ mail_domain }}"

denyhosts_branch: userdeffix
denyhosts_orgname: acjohnson
denyhosts_allowed_hosts:
  - homeserv.kristyandaaron.com
  - emby.thejohnsons.site
  - mail.pcdomain.com
  - 135.181.129.17
  - 195.201.96.41
  - 216.201.72.28
  - 216.201.72.47
