---
spamassassin_container_globals:
  registry_server: registry.thejohnsons.site
  image_name: debianbased
  image_tag: spamassassin-4.0.2
  container_command: ''
  container_log_driver: "json-file"
  container_log_options:
    max-size: "10m"
    max-file: "1"

spamassassin_containers:
  - container_name: spamassassin
    container_networks:
      - name: br-local
    container_exposed_ports:
      - 783
    container_published_ports:
      - 127.0.0.1:783:783/tcp
    container_volumes:
      - /docker/spamassassin:/etc/spamassassin
