---
roundcube_domain: example.com
roundcube_version: 1.4.7
roundcube_des_key: mustbe24charsinlength...
roundcube_archive: "roundcubemail-{{ roundcube_version }}-complete.tar.gz"
roundcube_url: "https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/{{ roundcube_archive }}"
roundcube_checksum: sha256:26d85d27ff7ef491de09168a27df74a5574b7dd4127e6c2822c90a108c6aacc9
roundcube_db_string: "sqlite:////var/sqlite3/roundcube-{{ roundcube_version }}/sqlite.db?mode=0640"
roundcube_plugins:
  - filters:
    url: https://github.com/6ec123321/filters/archive/master.zip
    extracted_folder: filters-master
    destination_folder: filters
