---
roundcube_domain: example.com
roundcube_version: 1.3.6
roundcube_des_key: mustbe24charsinlength...
roundcube_archive: "roundcubemail-{{ roundcube_version }}-complete.tar.gz"
roundcube_url: "https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/{{ roundcube_archive }}"
roundcube_checksum: sha256:f1b86e97cc8fd69bb1957d4115762af6ea2d6957ea17b33dd3ec2995662670d9
roundcube_db_string: "sqlite:////var/sqlite3/roundcube-{{ roundcube_version }}/sqlite.db?mode=0640"
roundcube_ssl_dir: /var/ssl/mail
roundcube_imap_ssl_ca_file: "{{ roundcube_ssl_dir }}/ca.pem"
roundcube_plugins:
  - filters:
    url: https://github.com/6ec123321/filters/archive/master.zip
    extracted_folder: filters-master
    destination_folder: filters
