---
roundcube_domain: example.com
roundcube_version: 1.4.1
roundcube_des_key: mustbe24charsinlength...
roundcube_archive: "roundcubemail-{{ roundcube_version }}-complete.tar.gz"
roundcube_url: "https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/{{ roundcube_archive }}"
roundcube_checksum: sha256:640423d21e1aa733ddea7462f156e194b051f086a3f2a70430e0aa2c9b09b44a
roundcube_db_string: "sqlite:////var/sqlite3/roundcube-{{ roundcube_version }}/sqlite.db?mode=0640"
roundcube_plugins:
  - filters:
    url: https://github.com/6ec123321/filters/archive/master.zip
    extracted_folder: filters-master
    destination_folder: filters
