---
roundcube_domain: example.com
roundcube_smtp_fqdn: "{{ fqdn_hostname }}"
roundcube_imap_fqdn: "{{ fqdn_hostname }}"
roundcube_version: 1.4.10
roundcube_des_key: mustbe24charsinlength...
roundcube_archive: "roundcubemail-{{ roundcube_version }}-complete.tar.gz"
roundcube_url: "https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/{{ roundcube_archive }}"
roundcube_checksum: sha256:a3d8c0dc4db70188f4aea3b62c1bd8b0b31b0c0f77f77138c0715e9d6ddd520f
roundcube_db_string: "sqlite:////var/sqlite3/roundcube-{{ roundcube_version }}/sqlite.db?mode=0640"
roundcube_plugins:
  - filters:
    url: https://github.com/6ec123321/filters/archive/master.zip
    extracted_folder: filters-master
    destination_folder: filters
  - twofactor_gauthenticator:
    url: https://github.com/alexandregz/twofactor_gauthenticator/archive/master.zip
    extracted_folder: twofactor_gauthenticator-master
    destination_folder: twofactor_gauthenticator
