---
roundcube_domain: example.com
roundcube_smtp_fqdn: "{{ fqdn_hostname }}"
roundcube_imap_fqdn: "{{ fqdn_hostname }}"
roundcube_version: 1.4.8
roundcube_des_key: mustbe24charsinlength...
roundcube_archive: "roundcubemail-{{ roundcube_version }}-complete.tar.gz"
roundcube_url: "https://github.com/roundcube/roundcubemail/releases/download/{{ roundcube_version }}/{{ roundcube_archive }}"
roundcube_checksum: sha256:d91490c55b357391efd3e10863bcdf897595df33a8c73faa2ea9df3391d06a4a
roundcube_db_string: "sqlite:////var/sqlite3/roundcube-{{ roundcube_version }}/sqlite.db?mode=0640"
roundcube_plugins:
  - filters:
    url: https://github.com/6ec123321/filters/archive/master.zip
    extracted_folder: filters-master
    destination_folder: filters
