---
- block:

  - name: Get list of mounted ext3/4 and xfs filesystems
    shell: |
      /usr/bin/awk '{if ($3 ~ /^ext.*/ || $3 == "xfs") print $2}' /proc/mounts | grep -v kubelet
    register: fstrim_filesystems

  - name: "Create recover-space.sh script"
    template:
      src: "recover-space.sh.j2"
      dest: "/opt/recover-space.sh"
      owner: "root"
      group: "root"
      mode: 0755

  - name: Enable recover-space.sh cron
    cron:
      name: "recover-space"
      minute: "{{59|random(seed=inventory_hostname)}}"
      hour: "1"
      job: "/opt/recover-space.sh > /var/log/recover-space.log 2>&1"

  become: yes
  become_user: root
