---
- name: Install ffmpeg
  package:
    name: ffmpeg
    state: latest

- name: "Recursively find {{ find_base }} files larger than {{ min_file_size }}"
  find:
    paths: "{{ find_base }}"
    size: "{{ min_file_size }}"
    patterns: "*.{{ files_list_item }}"
    excludes:
      - "*_RECODE.mp4"
      - "*_SKIP*"
    recurse: yes
  register: files_list
  loop_control:
    loop_var: files_list_item
  with_items:
   - mp4
   - mpeg4
   - mkv
   - avi

- name: "List of files to be encoded..."
  debug:
    msg: "{{ item[1].path }}"
  with_subelements:
    - "{{ files_list.results }}"
    - files

- name: "Iterate encode.yml tasks"
  include_tasks: encode.yml
  with_subelements:
    - "{{ files_list.results }}"
    - files
  tags:
   - do_encode
