---

- name: Install python-certbot-nginx and deps
  apt:
    name:
      - git
      - curl
      - wget
      - openssl
      - ca-certificates
      - build-essential
      - libffi-dev
      - libssl-dev
      - python-dev
      - python-setuptools
      - python-certbot-nginx
    state: latest
    update_cache: yes

- name: Create certbot user
  user:
    name: certbot
    state: present
    create_home: yes
    home: /opt/certbot
    shell: /bin/bash

- name: Create /opt/certbot directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: certbot
    group: certbot
  with_items:
    - /opt/certbot/logs
    - /opt/certbot/config
    - /opt/certbot/.config/letsencrypt

- name: Configure certbot
  template:
    src: cli.ini.j2
    dest: /opt/certbot/.config/letsencrypt/cli.ini
