---
pulsar_group_name: pulsar

docker_apt_arch: amd64
docker_apt_release_channel: stable

bootstrap_pulsar_zookeeper: False
bootstrap_pulsar_disk: False

pulsar_cluster_name: "local"

pulsar_web_service_port: 8080
pulsar_web_service_url: "{{ hostvars[groups[pulsar_group_name][0]].ansible_default_ipv4.address }}:{{ pulsar_web_service_port }}"
pulsar_broker_service_port: 6650
pulsar_broker_service_url: "{{ hostvars[groups[pulsar_group_name][0]].ansible_default_ipv4.address }}:{{ pulsar_broker_service_port }}"

pulsar_data_vol_size: 800g

pulsar_zookeeper_servers: "{{ groups[pulsar_group_name]|map('extract', hostvars, ['ansible_default_ipv4', 'address'])|map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"
