---
- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - sudo
    - lvm2
    - xfsprogs
    - mlocate
    - vim
    - git
    - tig
    - python-pip
    - pciutils
    - lshw
    - curl
    - binutils
    - unzip
    - rsync
    - strace

- name: Set fqdn hostname
  hostname:
    name: "{{ mail_fqdn_hostname }}"

- name: "sysctl - set swapiness"
  sysctl:
    name: vm.swappiness
    value: 5
    state: present

- name: "sysctl - disable IPv6"
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
    - net.ipv6.conf.eth0.disable_ipv6
