---
# https://packages.debian.org/bullseye-backports/amd64/spamc/download
# http://ftp.us.debian.org/debian/pool/main/s/spamassassin/spamc_4.0.0-1~bpo11+1_amd64.deb
spamc_package_name: 'spamc_4.0.0-1~bpo11+1_amd64.deb'
